[tool.black]
experimental_string_processing = true

[tool.pylint.MASTER]
generated-members = ["numpy.*", "torch.*"]
disable = ["C0411"]
ignore-paths = ["src/old", "src/utils/old", "scripts/old"]

[tool.isort]
profile = "black"
src_paths = "isort,test"
skip = ["src/old", "src/utils/old", "scripts/old"]

[tool.mypy]
exclude = ["tests","src/old","src/utils/old","scripts/old","src/utils/gcn_classification_utils\\.py"]
ignore_missing_imports = true
disallow_untyped_defs = true

