transformer_encoder:
  _target_: src.utils.pyg_model_zoo.TransformerEncoder
  in_dim: 600
  channels: 1 #Number of channels of cassette used for training
  hidden_dim: 8
  n_layers: 6
  nhead: 6
  n_classes: 6
  dropout: 0.1

transformer_encoder_adv:
  _target_: src.utils.pyg_model_zoo.TransformerAdv
  in_dim: 600
  channels: 1 #Number of channels of cassette used for training
  hidden_dim: 512
  n_layers: 6
  nhead: 8
  n_classes: 6
  dropout: 0.1


CNNClassifier:
  _target_: src.utils.pyg_model_zoo.CNNClassifier
  channels: 3 #Number of channels of cassette used for training
  in_dim: 600
  n_classes: 6
  num_filters: 64
  kernel_size: 3 
  pool_size: 2

RNNClassifier:
  _target_: src.utils.pyg_model_zoo.RNNClassifier
  in_dim: 1
  hidden_size: 32
  num_layers: 8
  num_classes: 6
  rnn_type: 'LSTM'


BiRNNClassifier:
  _target_: src.utils.pyg_model_zoo.BiRNNClassifier
  in_dim: 1  # Input dimensionality of each time step
  hidden_size: 32  # Hidden size of the RNN layer
  num_layers: 8  # Number of RNN layers
  num_classes: 6  # Number of output classes
  rnn_type: LSTM  # Choose either LSTM or GRU


StackedBiRNNClassifier:
  _target_: src.utils.pyg_model_zoo.StackedBiRNNClassifier
  in_dim: 1  # Input dimensionality of each time step
  hidden_size: 32  # Hidden size of the RNN layer
  num_layers: 8  # Number of RNN layers
  num_classes: 6  # Number of output classes
  rnn_type: LSTM  # Choose either LSTM or GRU



