transformer_encoder:
  _target_: src.utils.pyg_model_zoo.TransformerEncoder
  in_dim: 600
  channels: 1 #Number of channels of cassette used for training
  hidden_dim: 512
  n_layers: 6
  nhead: 8
  n_classes: 6
  dropout: 0.1

transformer_encoder_adv:
  _target_: src.utils.pyg_model_zoo.TransformerAdv
  in_dim: 600
  channels: 1 #Number of channels of cassette used for training
  hidden_dim: 512
  n_layers: 6
  nhead: 8
  n_classes: 6
  dropout: 0.1


CNNClassifier:
  _target_: src.utils.pyg_model_zoo.CNNClassifier
  channels: 1 #Number of channels of cassette used for training
  in_dim: 600
  n_classes: 6
  num_filters: 64
  kernel_size: 3 
  pool_size: 2

RNNClassifier:
  _target_: src.utils.pyg_model_zoo.RNNClassifier
  in_dim: 600
  num_layers:
  num_classes:
  rnn_type: 'LSTM'




