mlflow:
  tracking_uri: ${hydra:runtime.cwd}/mlflow_runs
  #tracking_uri: mlflow_runs
  experiment_name: test


training_params:
  n_classes: 6
  trainer_params:
    accumulate_grad_batches: 4
    early_stopping_patience: 5
    max_epochs: 5
    val_split: 0.15
    val: True
    limit_train_batches: None # run through only 25% of the training set each epoch
    overfit_batches: 4 # overfit on 10 of the same batches
    adversarial_attack: False
  data_module_params:
    batch_size: 32
    num_workers: 4
  optimization_params:
    l2_coeff: 5e-4
    lr_scheduler_gamma: 0.75
    lr_scheduler_step_size: 10
    lr: 5e-4
  
  features_list:
    #- EEG_Fpz-CZ
    #- EEG_PZ-Oz
    - EOG_horizontal
    #- EMB_submental
